<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dna.Framework" Version="1.0.7.18" />
    <PackageReference Include="Dna.Framework.AspNet" Version="1.0.7" />
    <PackageReference Include="Fody" Version="6.5.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="PropertyChanged.Fody" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApiModels\Services\" />
    <Folder Include="ApiModels\NewFolder1\" />
    <Folder Include="ApiModels\NewFolder\" />
    <Folder Include="DataModels\Finance\Investment\" />
  </ItemGroup>

</Project>
