<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ApiModels\NewFolder1\**" />
    <EmbeddedResource Remove="ApiModels\NewFolder1\**" />
    <None Remove="ApiModels\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.5.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MahApps.Metro" Version="1.6.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PropertyChanged.Fody" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataModels\Finance\Investment\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\repos\dna-framework\Source\Dna.Framework.AspNet\Dna.Framework.AspNet.csproj" />
    <ProjectReference Include="..\..\..\repos\dna-framework\Source\Dna.Framework\Dna.Framework.csproj" />
  </ItemGroup>

</Project>
