<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ApiModels\NewFolder1\**" />
    <EmbeddedResource Remove="ApiModels\NewFolder1\**" />
    <None Remove="ApiModels\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dna.Framework" Version="1.0.7.18" />
    <PackageReference Include="Dna.Framework.AspNet" Version="1.0.7" />
    <PackageReference Include="Fody" Version="6.5.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MahApps.Metro" Version="1.6.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="PropertyChanged.Fody" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataModels\Finance\Investment\" />
  </ItemGroup>

</Project>
